### ISSUE TITLE
Move Docs on symfony.com

### ISSUE THREAD

**Issue by ElectricMaxxx** [FriendsOfSymfony/FOSCKEditorBundle#10]
@javiereguiluz you would be the one, who could do that for us, right?

**Comment by javiereguiluz** [comment]
I'm not the one making these decisions (Fabien is) but I can tell you that bundles published on symfony.com must meet some conditions. They must have lots of GitHub stars (this one looks like it only has `1`), lots of downloads (I can't find this package in Packagist.org), etc. Also, when the bundle belongs to a crowded niche (like this one with CK editors) we only include "the reference bundle" in that niche.

I'm afraid this bundle doesn't meet the conditions (yet) ... but please don't be discouraged to keep working on it and continue improving it. Thanks!

**Comment by kunicmarko20** [comment]
@javiereguiluz We took over https://github.com/egeloen/IvoryCKEditorBundle which is abandoned and that bundle is already on symfony docs website.

**Comment by ElectricMaxxx** [comment]
@javiereguiluz this one is the copy of https://github.com/egeloen/IvoryCKEditorBundle and it still on symfon.com https://symfony.com/doc/current/bundles/IvoryCKEditorBundle/index.html

**Comment by ElectricMaxxx** [comment]
So we simply would be happy to switch your paths, when importing docs.

**Comment by javiereguiluz** [comment]
Next time, please don't hide important info like that one 😅 

We'll make the change on symfony.com then. Please tell me when you publish the package on Packagist.org, release a stable version and everything works. Thanks!

**Comment by ElectricMaxxx** [comment]
@javiereguiluz  we would like to go on RC-1 today together with the new (added some migration infos and namespace changes). You can find the new repo on packagist: https://packagist.org/packages/friendsofsymfony/ckeditor-bundle
The location of the docs is now under `docs/` as it is best practice. We will add some tests for doc building later that day, so i hope the build will be green on your side. Can you please change the link for us?

**Comment by javiereguiluz** [comment]
I'm on it. By the way, if I'm right, the consensus for modern bundles was to move `Resources/doc/` to `doc/` (in singular) ... not `docs/` (in plural)

**Comment by ElectricMaxxx** [comment]
@javiereguiluz now we are in the correct folder.

**Comment by kunicmarko20** [comment]
Thank you @javiereguiluz. 🎉 🎊
