### ISSUE TITLE
Anounce the changes

### ISSUE THREAD

**Issue by ElectricMaxxx** [FriendsOfSymfony/FOSCKEditorBundle#12]
ToDo:
* [x] symfony blog
* [x] own blogs
* [x] Twitter
* [x] Symfony Slack
* [x] ???

**Comment by ElectricMaxxx** [comment]
At least it shouldn't block the relase, but is a task related :-)

**Comment by ElectricMaxxx** [comment]
I would propose the following plan
- RC time until May the 3rd
- engage ro test via Twitter and slack
- test in sonata and cmf
- release on evening of may 3rd
- publish anouncement blog posts at moening of may the 4rh
- force a Symfony Live speaker to add a block for us

**Comment by kunicmarko20** [comment]
How are you gonna force someone to add a block? Don't like that part, else is ok

**Comment by ElectricMaxxx** [comment]
Force is a maybe to hard. It is half a joke. But at least one or two speakers are friends of mine. An i would ask them, if they would add a note to talk to me to thier closing section. 

Sure it won't be @fabpot it self, but maybe @derra

**Comment by derrabus** [comment]
At Symfony Live Phantasialand, I'm having a workshop with 25 attendees at most. I don't think that announcing anything there would be helpful for you. 😉

**Comment by ElectricMaxxx** [comment]
@javiereguiluz  can i have a Symfony blog post slot for that? Would wtite a short anouncement sith backgound why in symfony blog. And a longer one in an own blog.

**Comment by ElectricMaxxx** [comment]
thanks all involved.
