### ISSUE TITLE
FOSCKEditorBundle not working only in english, not in private mode , focus on text not working

### ISSUE THREAD

**Issue by lmasforne** [FriendsOfSymfony/FOSCKEditorBundle#125]
#### Symfony packages

Latest stable version (i think ckeditor 4.8.0)
```
composer require friendsofsymfony/ckeditor-bundle
php bin/console ckeditor:install
php bin/console assets:install web
```

## Subject

I've got a realy weird bug with Ckeditor, so :

I use this bundle :

https://symfony.com/doc/master/bundles/FOSCKEditorBundle/index.html

I have a multilanguage system and the bundle with CKEditor works fine on /fr, /es, /de but not in /en.

I have nothing special on the route /en.

The problem is on /en the editor is not focusable, when I click inside nothing append. When I check the element with the console, I can see on the iframe a class=display:none !important, And I can't remove this class, think it's from CKEditor.js

I try everything, clear all cache (sf/browser) , remove all js's, css etc ...

Nothing work.

Wich is very weird, it's work in private mode in english ????

I dont known how to fix this bug ?

If someone got an idea ?

thx

**Comment by kunicmarko20** [comment]
Closing as no reply.
