### ISSUE TITLE
Problem with uploading image using CKEditor

### ISSUE THREAD

**Issue by antonioperic** [FriendsOfSymfony/FOSCKEditorBundle#127]
##### Issue Type:

Please pick one and delete the rest:
 - Bug Report

##### Bundle Version:

Master or exact version, i.e. 8.0.3

##### Summary:

I integrated CKEditor with Elfinder bundle, and after I add image and save I got this error:

> An exception has been thrown during the rendering of a template ("Warning: html_entity_decode(): charset `L' not supported, assuming utf-8").

this happens only when I add an image via the editor, if I change the text or just copy paste image tag, everything works ok

##### Steps To Reproduce:

install FOSCKEditorBundle
Instal FMElfinder Bundle
configure
try add image
(note: I am working with sylius project)

my config
```

fm_elfinder:
    #assets_path: / # default is /assets, this is where css/js elfinder files are
    instances:
        default:
            locale: %locale%
            editor: ckeditor
            include_assets: true
            connector:
                debug: true
                roots:
                    uploads:
                        driver: LocalFileSystem
                        path: uploads
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']
                        upload_max_size: 8M

fos_ck_editor:
    default_config: app_ckeditor_config
    configs:
        app_ckeditor_config:
            height: 350px
            filebrowserBrowseRoute: elfinder
            filebrowserBrowseRouteParameters: []
```

**Comment by kunicmarko20** [comment]
Can you please provide a full stack trace.

**Comment by antonioperic** [comment]
That happens only if I go to elfinder, pick or upload image and add it to content

**Comment by kunicmarko20** [comment]
Just tested Ckeditor with Elfinder on Symfony and I did not have any problems, are you sure this is on ckeditor side? Based on that stack trace it seems error is coming from Sylius.

**Comment by antonioperic** [comment]
@kunicmarko20 not sure why is that happening, only in situation where I am choosing image from elfinder

**Comment by antonioperic** [comment]
will check on some other machine. That part of code is just render(controller(...
nothing so sylius specific, just regular symfony thing

**Comment by antonioperic** [comment]
seems that issue is related to local dev environment on OSX

**Comment by DylanDelobel** [comment]
Same issue on Unix

```
An exception has been thrown during the rendering of a template ("Warning: html_entity_decode(): charset `cli' not supported, assuming utf-8").


in vendor/symfony/symfony/src/Symfony/Bundle/WebProfilerBundle/Resources/views/Profiler/layout.html.twig (line 103)
```

**Comment by kunicmarko20** [comment]
Again the error is not coming from a ckeditor file, if you are sure everything works on your side. Please open a new issue
