### ISSUE TITLE
Plugin directory path conflicts with Symfony asset versioning strategy

### ISSUE THREAD

**Issue by foucdeg** [FriendsOfSymfony/FOSCKEditorBundle#128]
### Environment
Ubuntu 16.04, PHP 7.2, Symfony 3.4

#### Symfony packages

```
symfony/assetic-bundle     v2.8.2  v2.8.2 Integrates Assetic into Symfony2
Package symfony/assetic-bundle is abandoned, you should avoid using it. Use symfony/webpack-encore-pack instead.
symfony/monolog-bundle     v3.2.0  v3.3.0 Symfony MonologBundle
symfony/polyfill-apcu      v1.8.0  v1.8.0 Symfony polyfill backporting apcu_* functions to lower PHP...
symfony/polyfill-ctype     v1.8.0  v1.8.0 Symfony polyfill for ctype functions
symfony/polyfill-intl-icu  v1.8.0  v1.8.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.8.0  v1.8.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.8.0  v1.8.0 Symfony polyfill backporting some PHP 5.6+ features to low...
symfony/polyfill-php70     v1.8.0  v1.8.0 Symfony polyfill backporting some PHP 7.0+ features to low...
symfony/polyfill-util      v1.8.0  v1.8.0 Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.1  v3.0.1 Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.6.7  v3.2.2 Symfony SwiftmailerBundle
symfony/symfony            v3.4.11 v4.1.1 The Symfony PHP framework
```

## Subject

The rendering of the Javascript code necessary to load an external plugin, is broken by the default Symfony asset versioning strategy. The directory part of the plugin path that is written onto the `<script>` tag above the CKEditor field, has a version string appended as per [Symfony asset versioning](http://symfony.com/doc/current/components/asset.html#versioned-assets) (with a StaticVersionStrategy).

The responsible piece of code seems to be [here](https://github.com/FriendsOfSymfony/FOSCKEditorBundle/blob/1.x/src/Renderer/CKEditorRenderer.php#L379).

The [if clause below](https://github.com/FriendsOfSymfony/FOSCKEditorBundle/blob/1.x/src/Renderer/CKEditorRenderer.php#L381) does not fix the problem as my directory path does not end with `/`.

## Steps to reproduce

- Configure Symfony with a static asset versioning strategy

```
# config.yml
framework:
    assets:
        version: 1
```
- Install FOSCkEditorBundle
- Render a CKEditorType form field in a form
- Configure CKEditor with [YouTube plugin](https://ckeditor.com/cke4/addon/youtube) (for example)

```
# config.yml
fos_ck_editor:
    plugins:
        youtube:
            path: '/plugins/ckeditor/youtube'
            filename: 'plugin.js'
```

## Expected results

This is part of the <script> tag that should be rendered above the CKEditor field:
```
CKEDITOR.plugins.addExternal("menu", "/plugins/ckeditor/youtube", "plugin.js");
```
and therefore in the dev console, the request to the plugin file is to `plugins/ckeditor/youtube/plugin.js` -> succeeds

## Actual results

```
CKEDITOR.plugins.addExternal("menu", "/plugins/ckeditor/youtube?1", "plugin.js");
```

and therefore in the dev console, the request to the plugin file is to `plugins/ckeditor/youtube?1/plugin.js` -> 404

**Comment by foucdeg** [comment]
Update: my plugin directory config might need a trailing slash. This is unusual, but I'll try it.

**Comment by foucdeg** [comment]
@kunicmarko20 it did.
If I may suggest, it seems unusual in the Symfony ecosystem for directories to be specified with trailing slashes in config files. Usually they're specified without trailing slashes, which is why I missed this.
Perhaps directories specified without trailing slashes should be supported, or the documentation page should insist on the trailing slash.

**Comment by foucdeg** [comment]
@kunicmarko20 I've opened a pull request with a slight improvement of the documentation page.

https://github.com/FriendsOfSymfony/FOSCKEditorBundle/pull/129

**Comment by kunicmarko20** [comment]
Thank you.
