### ISSUE TITLE
Provide a way to suppress progress bar during installation

### ISSUE THREAD

**Issue by DanieleGBX** [FriendsOfSymfony/FOSCKEditorBundle#131]
Currently, when installing the editor, the progress bar floods log files unnecessarily, it is paramount that a way to remove it is provided.

**Comment by kunicmarko20** [comment]
I think this looks like a better option:

https://github.com/zicht/solr-bundle/commit/9648079008368b0f08163e45e4ee8a3033bf0133

This issue is that progress bar is writing to stderr instead of stdout (https://github.com/symfony/symfony/issues/18744)

Would you like to provide a PR?

**Comment by kunicmarko20** [comment]
After some investigating it seems that `symfony/console` already has this option, just add `--quite` as an option to your command and you won't see anything, read more about it [here](https://symfony.com/doc/current/console/verbosity.html)
