### ISSUE TITLE
Replace ResourceCompilerPass with Flex recipe

### ISSUE THREAD

**Issue by kunicmarko20** [FriendsOfSymfony/FOSCKEditorBundle#136]
https://github.com/FriendsOfSymfony/FOSCKEditorBundle/blob/43e0ec349cd809959f490d23e3e37b87c1314191/src/DependencyInjection/Compiler/ResourceCompilerPass.php#L28-L35

Twig is now mandatory so that `if` makes no sense. I do not like modifing parameters like this, before we didn't have recipes and this would remove 1 extra step, but now there is no need for this.

**Comment by kunicmarko20** [comment]
@ElectricMaxxx wdyt?

**Comment by ElectricMaxxx** [comment]
Let us do it in a reciepe.
