### ISSUE TITLE
doc: docs/usage/ckeditor.rst is outdated about configuration 

### ISSUE THREAD

**Issue by SimonHeimberg** [FriendsOfSymfony/FOSCKEditorBundle#151]
version: master (43e0ec349cd809959f490d23e3e37b87c1314191)

## docs/usage/ckeditor.rst is outdated about configuration 

The file [docs/usage/ckeditor.rst in master](https://github.com/FriendsOfSymfony/FOSCKEditorBundle/blob/43e0ec34/docs/usage/ckeditor.rst) is outdated about configuration. The mentioned keys in `extras` of `composer.json` only work with composer command. But this command is deprecated, it was removed from doc in 
43e0ec349cd809959f490d23e3e37b87c1314191.

## Expected
The code about the config in `extra` of `composer.json` is removed as well.

**Comment by kunicmarko20** [comment]
Thank you, fixed with #152.
