### ISSUE TITLE
deprecation (Symfony 3.4)

### ISSUE THREAD

**Issue by alexgoncharcherkassy** [FriendsOfSymfony/FOSCKEditorBundle#159]
Remaining vendors deprecation notices(33) 
in my test

The FOS\CKEditorBundle\ModelToolbarManagerInterface is deprecated since 1.x and will be removed with the 2.0 release.
The FOS\CKEditorBundle\ModelToolbarManager is deprecated since 1.x and will be removed with the 2.0 release.
And so on...

"name": "friendsofsymfony/ckeditor-bundle",
"version": "1.2.0",

**Comment by kunicmarko20** [comment]
Well, it is deprecated, don't understand the point of this issue? 2.0.0 will be released in the following weeks.

**Comment by kunicmarko20** [comment]
If you are bothered by the deprecation downgrade to 1.1 or just wait a bit for 2.0
