### ISSUE TITLE
the renderer should be usable without templating

### ISSUE THREAD

**Issue by stof** [FriendsOfSymfony/FOSCKEditorBundle#16]
The `renderTemplate` implementation depends on `symfony/templating`, but this package is not available by default in Flex projects

**Comment by kunicmarko20** [comment]
The only `renderTemplate` I saw was:

https://github.com/FriendsOfSymfony/FOSCKEditorBundle/blob/78fce30733b5bb45d8fea7d3b75a84e874e75116/Renderer/CKEditorRenderer.php#L136

And it is class in this repo, not `symfony/templating`?

**Comment by stof** [comment]
look at the *implementation* of this method. It relies on the templating component, without support for direct Twig usage.

**Comment by kunicmarko20** [comment]
Ah, I saw it just now. We should just drop templating and depend on twig directly.
