### ISSUE TITLE
Missing form theme while upgrading & in docs

### ISSUE THREAD

**Issue by jmsche** [FriendsOfSymfony/FOSCKEditorBundle#161]
Hi,

I upgraded the bundle from 1.x to 2.0 and something was missing as the recipe was not fired: the `twig.form_themes` configuration was not updated to add `@FOSCKEditor/Form/ckeditor_widget.html.twig`.

I think something should be added about this in upgrade and docs? Eg. for people upgrading or installing 2.x without installing recipe.

Thanks!

**Comment by kunicmarko20** [comment]
Hm, so if you upgrade a package you don't get a recipe? Also, this would probably happen for people not using flex, do you have time to provide a PR?

**Comment by jmsche** [comment]
I guess not. I just did the same update on an other project - from 1.2 to 2.0 - nothing was triggered.

Sure, I can provide a PR :)
