### ISSUE TITLE
Deprecations with Symfony 4.2

### ISSUE THREAD

**Issue by angelsk** [FriendsOfSymfony/FOSCKEditorBundle#167]
#### Symfony packages

symfony/symfony v4.2.0

## Subject

Deprecation notices

* A tree builder without a root node is deprecated since Symfony 4.2 and will not be supported anymore in 5.0.

## Steps to reproduce

Upgrade to Symfony 4.2

**Comment by kunicmarko20** [comment]
Hi @angelsk thank you for reporting this, there is already a PR that will fix it https://github.com/FriendsOfSymfony/FOSCKEditorBundle/pull/164
