### ISSUE TITLE
TextColor palette

### ISSUE THREAD

**Issue by jzeff** [FriendsOfSymfony/FOSCKEditorBundle#178]
Hi all, 

is it possible to restrict color palette for "TextColor" option please? I'm using symfony 4.

Thank you,
Jozef

**Comment by kunicmarko20** [comment]
We try to keep github issues for bug reports or feature requests. Please use Stackoverflow or find us on Symfony Slack channel.

**Comment by kunicmarko20** [comment]
CKEditor 4 is using https://ckeditor.com/cke4/addon/colorbutton plugin for the color palette.

You can set https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-colorButton_colors like this.
