### ISSUE TITLE
Support for custom builds in ckeditor:install

### ISSUE THREAD

**Issue by TomaszGasior** [FriendsOfSymfony/FOSCKEditorBundle#180]
## Feature Request

Currently `ckeditor:install` console command supports downloading prebuild official releases — basic, standard and full. I would suggest to support also custom builds which are generated by CKEditor website. 

Each custom build has its own ID which can be used as part of URL. For example, my own custom build generated on official ckeditor website has ID 5af1ea2fd3c9442ab08af09ec2423ce6 and it's possible to download it using this URL: http://ckeditor.com/builder/download/5af1ea2fd3c9442ab08af09ec2423ce6 Information about this feature (and build ID) is placed inside `build-config.js` file in generated archive.

From user perspective this can be implemented by adding to `ckeditor:install` command new option called `--build` with build ID as value. Of course, `--build` and `--release` could not be used at the same time.

**Comment by kunicmarko20** [comment]
I would rather add a new release option `custom` and a new option `custom_build_id` and then:

https://github.com/FriendsOfSymfony/FOSCKEditorBundle/blob/ca2b528d9a9939ca068fa01f0cddbce6cebcff13/src/Installer/CKEditorInstaller.php#L160

here check if it is a custom build, and if the id is not set, throw an exception.

Would you be interested in contributing this feature?
