### ISSUE TITLE
Plugin support I18n?

### ISSUE THREAD

**Issue by qwwdezone** [FriendsOfSymfony/FOSCKEditorBundle#182]
Hello, I add the Emoji plugin for ckeditor, but the plugin language always be English. I check the source , I didn't find the plugin setLang Method. Can you fix it?

**Comment by qwwdezone** [comment]
> Hello, I add the Emoji plugin for ckeditor, but the plugin language always be English. I check the source , I didn't find the plugin setLang Method. Can you fix it?

Yes, I had add the language js file for the plugin.

**Comment by kunicmarko20** [comment]
This has nothing to do with this bundle, the plugin needs to support I18n.
