### ISSUE TITLE
Reconsider min requirements

### ISSUE THREAD

**Issue by stof** [FriendsOfSymfony/FOSCKEditorBundle#19]
currently, the min requirements of the bundle are Symfony 2.7 (and even 2.0 for some components, but I doubt it works due to other requirements) and 5.6 for PHP.

We should at least review these to decide what we do in our new major version

**Comment by kunicmarko20** [comment]
I don't think we should support 2 LTS version so the minimum symfony could be 3.4. I would like to go with PHP 7.1 as the minimum but I am not sure if that is ok?

**Comment by kunicmarko20** [comment]
@ElectricMaxxx @fbourigault wdyt?

**Comment by ElectricMaxxx** [comment]
i see it also from a perspective of CI and there use ?`dist: trusty` for php 5.6 only, which makes it slow. We removed 5.6 and even 7.0 on CMF and Sonata, too. so a big :+1: from me.

**Comment by javiereguiluz** [comment]
Given that this is a new bundle (even technically speaking is a migration of an existing bundle) why not go for Symfony 4 and PHP 7.1 as min requirements?

**Comment by kunicmarko20** [comment]
@javiereguiluz The idea was that 1.0.0 was almost the same as `IvoryCKEditorBundle` but with support for Symfony4 so people can easier migrate to it, 2.0.0 release would clean the bundle and address all the issues.
