### ISSUE TITLE
CKEditor 5 support

### ISSUE THREAD

**Issue by napestershine** [FriendsOfSymfony/FOSCKEditorBundle#210]
Hi

Thanks for this awesome bundle

is it possible to get support for CKEditor 5?

Thanks

**Comment by haivala** [comment]
Has someone investigated this?
I installed the frontend part from 5 but it did not work at all.

**Comment by cedricplaire** [comment]
the file structure is not the same, I am currently looking for a simple solution. otherwise, I would wait for this beautiful team to update its bundle

**Comment by zoomtronic** [comment]
@cedricplaire  did you manage to get Ckeditor 5 working ?

**Comment by lsmith77** [comment]
duplicate of https://github.com/FriendsOfSymfony/FOSCKEditorBundle/issues/94
