### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by jmsche** [FriendsOfSymfony/FOSCKEditorBundle#222]
## Feature Request

It would be nice to add support to PHP 8 :)

Several questions to raise here:

* drop Symfony 3.4 support? last 3.4 bugfix release is next week IIRC
* replace Travis with Github Actions?
* what about phpstan? I see the CI allows failures for this run, but should it? maybe lower its level?

**Comment by VincentLanglet** [comment]
Do you want to work on this @jmsche ?

I see no real activity on this repo since one year. Is it still maintained @lsmith77 ? :)

**Comment by lsmith77** [comment]
I was never active on this Bundle (IIRC) but to the questions above:
1) yeah I am fine dropping support for 3.4, requiring 4.4+ and 5.1+ (or even 5.2+)
2) yeah Travis is dead for OSS :(
3) sure, feel free to tweak things, always better to make it pass and then slowly aim for higher levels

**Comment by jmsche** [comment]
@lsmith77 Thanks for your answers :) 

@VincentLanglet Feel free to work on this; my holidays started yesterday so I might find time for this, but I don't know when exactly :)

**Comment by VincentLanglet** [comment]
> I was never active on this Bundle (IIRC) 

Sorry, I didn't know who was maintaining this and you merged the last PR.
