### ISSUE TITLE
Bump php version?

### ISSUE THREAD

**Issue by Chris53897** [FriendsOfSymfony/FOSCKEditorBundle#234]
Hi. Is there any interest to bump php version to ^7.4|^8.0" as supported Versions. https://php.watch/versions
I could do the PR

**Comment by 0x6d6c** [comment]
Support for **PHP 8.0** has been added in #223. Possible duplicate of #222.

**Comment by lsmith77** [comment]
fixed via https://github.com/FriendsOfSymfony/FOSCKEditorBundle/pull/258
