### ISSUE TITLE
Separate accessors and mutators

### ISSUE THREAD

**Issue by stof** [FriendsOfSymfony/FOSCKEditorBundle#24]
This bundle (at least for the FormType) is using the same method for the accessor and the mutator, based on whether a non-null value is provided.
Such kind of API is quite uncommon in the Symfony ecosystem (and harder to typehint)

**Comment by kunicmarko20** [comment]
I am checking this and it seems it is used:

https://github.com/FriendsOfSymfony/FOSCKEditorBundle/blob/838aa9a6925ee00342f8f6e52a43881bf869a257/src/DependencyInjection/FOSCKEditorExtension.php#L86-L96

to just move the bundle config into form type. I think this can be done by just injecting the config into the form type instead, no need for accessors/mutators at all.

cc @ElectricMaxxx wdyt?
