### ISSUE TITLE
Symfony 6 compatibility

### ISSUE THREAD

**Issue by yanngallis** [FriendsOfSymfony/FOSCKEditorBundle#240]
Hi, 

I've tried to install FOSCKEditorBundle with Symfony 6 but i've got this incompatibility message :

` Problem 1
    - Root composer.json requires friendsofsymfony/ckeditor-bundle ^2.3 -> satisfiable by friendsofsymfony/ckeditor-bundle[2.3.0].
    - friendsofsymfony/ckeditor-bundle 2.3.0 requires symfony/asset ^4.4 || ^5.0 -> found symfony/asset[v4.4.0, ..., v4.4.27, v5.0.0, ..., v5.4.0] but it conflicts with your root composer.json require (6.0.*).`

Is there any plan for Symfony 6 compatibility ?

Thanks

**Comment by 0x6d6c** [comment]
This issue has already a PR #239.
