### ISSUE TITLE
Rework the way the model managers are working

### ISSUE THREAD

**Issue by stof** [FriendsOfSymfony/FOSCKEditorBundle#25]
Currently, all the model services (except the ToolbarManager) are stateful mutable objects, which are cloned in the form type before being mutated. This makes them unsuited for being registered as services (the way they are used does not correspond to services).

These services should become builder objects instantiated at the right time in the form type (a factory service might be provided in case this needs to be an extension point)

**Comment by kunicmarko20** [comment]
Most of this Managers have methods that are not used at all, and the point is just to set the default config and if there is a different one set at form options, then overwrite the config. Again, not sure if we even need some kind of service for this, or maybe just 1 service that can merge the config. WIll look more into this and find a better solution.

**Comment by kunicmarko20** [comment]
I just got into it more, basically, after merging https://github.com/FriendsOfSymfony/FOSCKEditorBundle/pull/134 we will have all the config in the form type, so I do not see the point of having any manager at all. Config can still be handled in Bundle Extension and then injected into form type (like it is done in #134) and all the Managers can get removed. cc @ElectricMaxxx
