### ISSUE TITLE
Will there be Symfony 7 support?

### ISSUE THREAD

**Issue by BackNot** [FriendsOfSymfony/FOSCKEditorBundle#257]
Hello, will there be Symfony 7 support?

**Comment by icemaker** [comment]
+1

**Comment by fouadSalkini** [comment]
I have added a **temporarily** bundle with SF7 support.

[https://github.com/fouadSalkini/FOSCKEditorBundle](https://github.com/fouadSalkini/FOSCKEditorBundle)

**Warning**
This bundle is only temporary and will only work as long as FOS does not add support for Symfony 7. It will then be removed after that

**Comment by lsmith77** [comment]
fixed via https://github.com/FriendsOfSymfony/FOSCKEditorBundle/pull/258
