### ISSUE TITLE
Lazy-load the command in Symfony 3.4+

### ISSUE THREAD

**Issue by stof** [FriendsOfSymfony/FOSCKEditorBundle#27]
The command is defined as a service (which is needed to support Symfony 4). But it is currently not lazy-loaded, because the name is not accessible at compile time.

there is 2 ways to fix this:

- provide the command name in the tag registering the command (thanks to the `alias` attribute)
- set the name in a static property (check the Symfony 3.4+ codebase to find the name of this property in the Command class, I don't remember it right now)

**Comment by ElectricMaxxx** [comment]
we currently support symfony/lte:2.* which means we would have to use duplicated code or some conditions to use features from Symfony 3.4 and above. We should talk about dropping SF-2 support on 2.0 of this bundle, which can possibly be the next :-)

**Comment by stof** [comment]
well, the only thing you would have to duplicate is the command name, to have it both in `configure` and in the externally-accessible location (and if you go for the static property rather than the tag attribute, you can even remove this duplication by reading the property).

**Comment by stof** [comment]
Symfony 3.3 and older would not know how to read the tag attribute containing the name or the static property, but they will not complain about them.

**Comment by enekochan** [comment]
The static property name is [`$defaultName`](https://github.com/symfony/symfony-docs/blob/master/console/commands_as_services.rst#lazy-loading)

**Comment by stof** [comment]
This does not need to go in a v2. It is not a BC break, and so could go in a 1.x release (it is part of having proper Symfony 4 support)

**Comment by fbourigault** [comment]
I have a preference to use the DI tag attribute over the static property name because it's all about dependency-injection.
