### ISSUE TITLE
What should come first?

### ISSUE THREAD

**Issue by ElectricMaxxx** [FriendsOfSymfony/FOSCKEditorBundle#28]
In chat @kunicmarko20 an i had a discussion what to include into a v1.0. What do you think?
From my POV, i would see a goal having a release as fast as possible, which means:
- fixes to get bundle working and consistent
- SF4 comaptibility
Doing so we would have a smal step only for migration from former repo to this one. I know that we have several ideas and stuff which needs to be fixed – even with BC-breaks. But lets get it out and work on a new major afterwards, what do you think?

At least we should have something stable to get the other bundles/packages like CMF, Sonata, into the road of releasing their SF4 compatible versions.

**Comment by kunicmarko20** [comment]
At first, I thought that we should handle everything before the release of `1.0.0` but maybe @ElectricMaxxx is right, we could just do the needed tasks that would allow people to use the Bundle with sf4 support and then start working on new major where we would fix everything.

This would also allow people to easily migrate from Ivory to FOS.

**Comment by kunicmarko20** [comment]
cc @fbourigault @xabbuh @stof

**Comment by xabbuh** [comment]
For example, I would not change the namespace before the release of 1.0. Doing so would mean making it unnecessarily hard to users to adopt the new package. IMO the primary goal should be to allow an easy transition and to provide support for modern Symfony versions.

**Comment by kunicmarko20** [comment]
So, you think we should release 1.0 with just sf4 support and we then start on 2.0?

**Comment by xabbuh** [comment]
I am even not sure that you really need to break BC. Is there anything you are planning that requires the major version bump? For the namespace change, you should be able to provide a BC layer using `class_alias()`.

**Comment by kunicmarko20** [comment]
If you check the issues, you will see there are a lot of stuff, some are BC breaks. I would rather allow people 1.0 for now just so they can still use CKEditor, and clean things with 2.0.

**Comment by stof** [comment]
Well, having a FOS package with a 1.0 release under a different namespace looks wrong to me. Migrating to the namespace should be done at the time they migrate to FOS

**Comment by kunicmarko20** [comment]
We would change the namespace, we would just add `class_alias` for the old namespace, to make the transition easier.

**Comment by kunicmarko20** [comment]
@ElectricMaxxx this can be closed?
