### ISSUE TITLE
Move Namespaces to Fos

### ISSUE THREAD

**Issue by ElectricMaxxx** [FriendsOfSymfony/FOSCKEditorBundle#3]

**Comment by xabbuh** [comment]
Do you really want to do that in a first stable release? That's another hurdle for current users to switch the bundle? At least, having class aliases for the old namespace would be a good idea IMO to ease the transition process.

**Comment by ElectricMaxxx** [comment]
if that one would be a break for a user which simply wanna use this bundle with SF4, we should not do it. Can you please make a note in #28 to create the tasks to do first in the comment there.

**Comment by ElectricMaxxx** [comment]
so what would be the solution for the aliases?
would that mean one alias `old` -> `new` for each class?  or one for each class, which is really used as a kind of a API on the bundle?

**Comment by kunicmarko20** [comment]
I would go with all classes get `new` namespace and we do alias for every class to `old` namespace.

**Comment by ElectricMaxxx** [comment]
close due #40
