### ISSUE TITLE
Add phpunit groups

### ISSUE THREAD

**Issue by kunicmarko20** [FriendsOfSymfony/FOSCKEditorBundle#31]
I suggest we add ` @group` to tests that run install and download stuff, for me at least, build takes so much time locally and I do not want to wait that long to confirm if I broke stuff.

Adding `@group installation` to:

https://github.com/FriendsOfSymfony/FOSCKEditorBundle/blob/master/Command/CKEditorInstallerCommand.php
and
https://github.com/FriendsOfSymfony/FOSCKEditorBundle/blob/master/Installer/CKEditorInstaller.php

would allow us to run tests with `phpunit  --exclude-group installation` and build is done in 15 seconds, and then we leave travis to confirm if installation works.

**Comment by kunicmarko20** [comment]
Also, maybe we can have just one run that would test this installation as currently, some runs hang because of that.

**Comment by ElectricMaxxx** [comment]
Nice indeed, this would be away to do the download on each test.

**Comment by ElectricMaxxx** [comment]
we could add the option to `PHPUNIT_FLAGS` environment when needed, yes makes sense. :-)
