### ISSUE TITLE
Test documentation 

### ISSUE THREAD

**Issue by ElectricMaxxx** [FriendsOfSymfony/FOSCKEditorBundle#43]
We should implement a linter and a build test for docs. Escpecially when i start edititng the rst stuff, there are plenty options to break the docs.

**Comment by ElectricMaxxx** [comment]
Mhh. 
@stof maybe knows how to handle doc building tests in. a travis cinfig accepting best practices?

**Comment by kunicmarko20** [comment]
I already provided PR to go back to scripts, we can wait for @stof and see if he knows, if not, I have ready a follow-up PR that will add docs test.
