### ISSUE TITLE
Broken master build - lowest dependencies with AbstractExtension

### ISSUE THREAD

**Issue by ElectricMaxxx** [FriendsOfSymfony/FOSCKEditorBundle#46]
### Environment
- Travis build
- php 5.6 and php 7.0 with lowest dependencies

## Steps to reproduce
- https://travis-ci.org/FriendsOfSymfony/FOSCKEditorBundle/builds/372274468?utm_source=email&utm_medium=notification
## Expected results
- green build
## Actual results

I think we should introduce the `AbstractExtension` with a condition or increase min twig version.

**Comment by kunicmarko20** [comment]
This was fixed.
