### ISSUE TITLE
Folder restructure

### ISSUE THREAD

**Issue by kunicmarko20** [FriendsOfSymfony/FOSCKEditorBundle#7]
Move code to `src`.

**Comment by stof** [comment]
@kunicmarko20 @ElectricMaxxx I suggest to do this one and #7 as soon as possible (but one after the other to avoid conflicts). These 2 tasks are the one which would conflict with any other changes. This way, it would allow to start accepting contributions from multiple devs.

**Comment by ElectricMaxxx** [comment]
@stof you referenced same issue :-)

**Comment by ElectricMaxxx** [comment]
But you are completely right. Other Tickets could be done individually then.

**Comment by kunicmarko20** [comment]
The second issue is probably namespace change and I agree also, that 2 are the most important ones.

**Comment by stof** [comment]
Yeah, I wanted to mention #3 but I messed up

**Comment by ElectricMaxxx** [comment]
![selection_234](https://user-images.githubusercontent.com/2905834/39308179-1b66f14e-4965-11e8-95fb-9ee06e5b20da.jpg)
this one?
