### ISSUE TITLE
Drop egeloen/json-builder

### ISSUE THREAD

**Issue by kunicmarko20** [FriendsOfSymfony/FOSCKEditorBundle#8]

**Comment by kunicmarko20** [comment]
Still didn't take a look at what that is even doing, but IIRC it is used only in renderer?

**Comment by ElectricMaxxx** [comment]
I also found the dependency only, when fixing the inhection of the rendere. So then lets see what it dors and decide latee what todo.

**Comment by kunicmarko20** [comment]
I am doing the namespace thing currently, I can take a look after or tomorrow. I just now found that it is also used in `Template` tests
