### ISSUE TITLE
Flex reciepe or not?

### ISSUE THREAD

**Issue by ElectricMaxxx** [FriendsOfSymfony/FOSCKEditorBundle#87]
Lets discuss and possibly implement.

**Comment by kunicmarko20** [comment]
Maybe we create a config that is commented out, as example? I think I saw some bundles do that

**Comment by ElectricMaxxx** [comment]
No, that is not recomented. So accept, we do not need it :-)

**Comment by covex-nn** [comment]
`egeloen/ckeditor-bundle` has its own recipe. A default toolbar is configured there, see its [default configuration](https://github.com/symfony/recipes-contrib/blob/master/egeloen/ckeditor-bundle/5.0/config/packages/ivory_ck_editor.yaml). Maybe a same recipe should be created for this package?

**Comment by ElectricMaxxx** [comment]
We discussed it Yesterday. Is it ok to have a reciepe because of an example usage or not. We were not sure if it is.

**Comment by kunicmarko20** [comment]
Is that really needed? It works without configuration, don't see the point of forcing it on people, if they want configuration, they can check the docs. I see flex recipes helping with the configuration you HAVE to add for the bundle to work
