### ISSUE TITLE
Migration : composer install?

### ISSUE THREAD

**Issue by fbourigault** [FriendsOfSymfony/FOSCKEditorBundle#93]
https://github.com/FriendsOfSymfony/FOSCKEditorBundle/blob/76830d56a8809dfc0dc4335c8839db3a957b83d7/docs/migration.rst#L35

Wouldn't this only complain about lock file being outdated?

**Comment by ElectricMaxxx** [comment]
you mean we should do:
```
composer remove egeloen/ckeditor-bundle -> wait
composer require friensofsymfony/ckeditor-bundle
```

instead?

**Comment by kunicmarko20** [comment]
`composer update`?
