### ISSUE TITLE
Evaluate CKEditor 5

### ISSUE THREAD

**Issue by ElectricMaxxx** [FriendsOfSymfony/FOSCKEditorBundle#94]
We want to evaluate the newer CKEditor 5. So we want to know how much work it would be and if we can use the current codebase to do so. Lets evaluate and writte down some data from CKEditor 5 docs or by installing and experimenting with an example. We should document it, here in the issue or in wiki section of the package.

**Comment by pierre-H** [comment]
Hello !
Any news ?

**Comment by napestershine** [comment]
Any new update ???

**Comment by msrumon** [comment]
That would be fantastic! Looking forward to the update of this discussion.

**Comment by iatanasov77** [comment]
Hello !
Any news ?

I waiting too for this bundle to support Ckeditor5

**Comment by stof** [comment]
Closing this. A bundle adding support for CKEditor 5 should do it by integrating in the Symfony UX ecosystem, not by updating this bundle.
